//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 11:12:34 PM BST 
//


package com.javainuse.models;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AnswerContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AnswerContainer">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}TaskContainer">
 *       &lt;attribute name="referenced_notification_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *       &lt;attribute name="server_response_type" use="required" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}SOAP_ServerError" />
 *       &lt;attribute name="version" type="{http://www.w3.org/2001/XMLSchema}decimal" fixed="1.0" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AnswerContainer")
public class AnswerContainer
    extends TaskContainer
{

    @XmlAttribute(name = "referenced_notification_ID", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long referencedNotificationID;
    @XmlAttribute(name = "server_response_type", required = true)
    protected SOAPServerError serverResponseType;
    @XmlAttribute(name = "version")
    protected BigDecimal version;

    /**
     * Gets the value of the referencedNotificationID property.
     * 
     */
    public long getReferencedNotificationID() {
        return referencedNotificationID;
    }

    /**
     * Sets the value of the referencedNotificationID property.
     * 
     */
    public void setReferencedNotificationID(long value) {
        this.referencedNotificationID = value;
    }

    /**
     * Gets the value of the serverResponseType property.
     * 
     * @return
     *     possible object is
     *     {@link SOAPServerError }
     *     
     */
    public SOAPServerError getServerResponseType() {
        return serverResponseType;
    }

    /**
     * Sets the value of the serverResponseType property.
     * 
     * @param value
     *     allowed object is
     *     {@link SOAPServerError }
     *     
     */
    public void setServerResponseType(SOAPServerError value) {
        this.serverResponseType = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVersion() {
        if (version == null) {
            return new BigDecimal("1.0");
        } else {
            return version;
        }
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVersion(BigDecimal value) {
        this.version = value;
    }

}
