//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 11:12:34 PM BST 
//


package com.javainuse.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClearZoneNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ClearZoneNotification">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}NotificationWithOSDState">
 *       &lt;sequence>
 *         &lt;element name="clear_zone_id" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ClearZoneID"/>
 *       &lt;/sequence>
 *       &lt;attribute name="is_blocked" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ClearZoneNotification", propOrder = {
    "clearZoneId"
})
public class ClearZoneNotification
    extends NotificationWithOSDState
{

    @XmlElement(name = "clear_zone_id", required = true)
    protected ClearZoneID clearZoneId;
    @XmlAttribute(name = "is_blocked", required = true)
    protected boolean isBlocked;

    /**
     * Gets the value of the clearZoneId property.
     * 
     * @return
     *     possible object is
     *     {@link ClearZoneID }
     *     
     */
    public ClearZoneID getClearZoneId() {
        return clearZoneId;
    }

    /**
     * Sets the value of the clearZoneId property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearZoneID }
     *     
     */
    public void setClearZoneId(ClearZoneID value) {
        this.clearZoneId = value;
    }

    /**
     * Gets the value of the isBlocked property.
     * 
     */
    public boolean isIsBlocked() {
        return isBlocked;
    }

    /**
     * Sets the value of the isBlocked property.
     * 
     */
    public void setIsBlocked(boolean value) {
        this.isBlocked = value;
    }

}
