//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 11:12:34 PM BST 
//


package com.javainuse.models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DateType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DateType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DATE_DONT_CARE"/>
 *     &lt;enumeration value="DATE_DAY_OF_WEEK"/>
 *     &lt;enumeration value="DATE_DAY_OF_MONTH"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DateType")
@XmlEnum
public enum DateType {

    DATE_DONT_CARE,
    DATE_DAY_OF_WEEK,
    DATE_DAY_OF_MONTH;

    public String value() {
        return name();
    }

    public static DateType fromValue(String v) {
        return valueOf(v);
    }

}
