//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 11:12:34 PM BST 
//


package com.javainuse.models;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FillEventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FillEventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="FILL_EVENT_ABOVE_THRESHOLD"/>
 *     &lt;enumeration value="FILL_EVENT_BELOW_THRESHOLD"/>
 *     &lt;enumeration value="FILL_EVENT_ANY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FillEventType")
@XmlEnum
public enum FillEventType {

    FILL_EVENT_ABOVE_THRESHOLD,
    FILL_EVENT_BELOW_THRESHOLD,
    FILL_EVENT_ANY;

    public String value() {
        return name();
    }

    public static FillEventType fromValue(String v) {
        return valueOf(v);
    }

}
