//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 11:12:34 PM BST 
//


package com.javainuse.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaskSubscribeTriggeredSafe complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskSubscribeTriggeredSafe">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}TaskSubscribeTriggered">
 *       &lt;attribute name="store_on_transmission_error" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskSubscribeTriggeredSafe")
@XmlSeeAlso({
    TaskSubscribeCountChannels.class,
    TaskSubscribeZoneStatistics.class,
    TaskSubscribeAlertInfo.class,
    TaskSubscribeCounting.class,
    TaskSubscribeClearZone.class,
    TaskSubscribeDigitalInput.class,
    TaskSubscribeFill.class,
    TaskSubscribeZoneChannels.class
})
public abstract class TaskSubscribeTriggeredSafe
    extends TaskSubscribeTriggered
{

    @XmlAttribute(name = "store_on_transmission_error")
    protected Boolean storeOnTransmissionError;

    /**
     * Gets the value of the storeOnTransmissionError property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isStoreOnTransmissionError() {
        if (storeOnTransmissionError == null) {
            return false;
        } else {
            return storeOnTransmissionError;
        }
    }

    /**
     * Sets the value of the storeOnTransmissionError property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setStoreOnTransmissionError(Boolean value) {
        this.storeOnTransmissionError = value;
    }

}
