//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 11:12:34 PM BST 
//


package com.javainuse.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.Duration;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for TaskSetVideoRecording complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskSetVideoRecording">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}Task">
 *       &lt;attribute name="recording_start" use="required" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="recording_duration" use="required" type="{http://www.w3.org/2001/XMLSchema}duration" />
 *       &lt;attribute name="recording_repetition" use="required" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}RepetitionCycle" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskSetVideoRecording")
public class TaskSetVideoRecording
    extends Task
{

    @XmlAttribute(name = "recording_start", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar recordingStart;
    @XmlAttribute(name = "recording_duration", required = true)
    protected Duration recordingDuration;
    @XmlAttribute(name = "recording_repetition", required = true)
    protected RepetitionCycle recordingRepetition;

    /**
     * Gets the value of the recordingStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRecordingStart() {
        return recordingStart;
    }

    /**
     * Sets the value of the recordingStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRecordingStart(XMLGregorianCalendar value) {
        this.recordingStart = value;
    }

    /**
     * Gets the value of the recordingDuration property.
     * 
     * @return
     *     possible object is
     *     {@link Duration }
     *     
     */
    public Duration getRecordingDuration() {
        return recordingDuration;
    }

    /**
     * Sets the value of the recordingDuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link Duration }
     *     
     */
    public void setRecordingDuration(Duration value) {
        this.recordingDuration = value;
    }

    /**
     * Gets the value of the recordingRepetition property.
     * 
     * @return
     *     possible object is
     *     {@link RepetitionCycle }
     *     
     */
    public RepetitionCycle getRecordingRepetition() {
        return recordingRepetition;
    }

    /**
     * Sets the value of the recordingRepetition property.
     * 
     * @param value
     *     allowed object is
     *     {@link RepetitionCycle }
     *     
     */
    public void setRecordingRepetition(RepetitionCycle value) {
        this.recordingRepetition = value;
    }

}
