//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.20 at 11:12:34 PM BST 
//


package com.javainuse.models;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Trigger complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Trigger">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="event_trigger" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}EventTrigger"/>
 *         &lt;element name="time_trigger" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}TimeTrigger"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Trigger", propOrder = {
    "eventTrigger",
    "timeTrigger"
})
public class Trigger {

    @XmlElement(name = "event_trigger")
    protected EventTrigger eventTrigger;
    @XmlElement(name = "time_trigger")
    protected TimeTrigger timeTrigger;

    /**
     * Gets the value of the eventTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link EventTrigger }
     *     
     */
    public EventTrigger getEventTrigger() {
        return eventTrigger;
    }

    /**
     * Sets the value of the eventTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTrigger }
     *     
     */
    public void setEventTrigger(EventTrigger value) {
        this.eventTrigger = value;
    }

    /**
     * Gets the value of the timeTrigger property.
     * 
     * @return
     *     possible object is
     *     {@link TimeTrigger }
     *     
     */
    public TimeTrigger getTimeTrigger() {
        return timeTrigger;
    }

    /**
     * Sets the value of the timeTrigger property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeTrigger }
     *     
     */
    public void setTimeTrigger(TimeTrigger value) {
        this.timeTrigger = value;
    }

}
