//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ClearZoneEventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ClearZoneEventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CLEAR_ZONE_EVENT_FREE"/>
 *     &lt;enumeration value="CLEAR_ZONE_EVENT_BLOCKED"/>
 *     &lt;enumeration value="CLEAR_ZONE_EVENT_ANY"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ClearZoneEventType")
@XmlEnum
public enum ClearZoneEventType {

    CLEAR_ZONE_EVENT_FREE,
    CLEAR_ZONE_EVENT_BLOCKED,
    CLEAR_ZONE_EVENT_ANY;

    public String value() {
        return name();
    }

    public static ClearZoneEventType fromValue(String v) {
        return valueOf(v);
    }

}
