//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CountEvent complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CountEvent">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="count_event_type" use="required" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}CountEventType" />
 *       &lt;attribute name="delta" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" default="1" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CountEvent")
public class CountEvent {

    @XmlAttribute(name = "count_event_type", required = true)
    protected CountEventType countEventType;
    @XmlAttribute(name = "delta")
    @XmlSchemaType(name = "unsignedInt")
    protected Long delta;

    /**
     * Gets the value of the countEventType property.
     * 
     * @return
     *     possible object is
     *     {@link CountEventType }
     *     
     */
    public CountEventType getCountEventType() {
        return countEventType;
    }

    /**
     * Sets the value of the countEventType property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountEventType }
     *     
     */
    public void setCountEventType(CountEventType value) {
        this.countEventType = value;
    }

    /**
     * Gets the value of the delta property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public long getDelta() {
        if (delta == null) {
            return  1L;
        } else {
            return delta;
        }
    }

    /**
     * Sets the value of the delta property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setDelta(Long value) {
        this.delta = value;
    }

}
