//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CountEventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CountEventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="COUNT_EVENT_ALWAYS"/>
 *     &lt;enumeration value="COUNT_EVENT_DELTA_IN"/>
 *     &lt;enumeration value="COUNT_EVENT_DELTA_OUT"/>
 *     &lt;enumeration value="COUNT_EVENT_DELTA_SUM_IN_OUT"/>
 *     &lt;enumeration value="COUNT_EVENT_DELTA_MAX_IN_OUT"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CountEventType")
@XmlEnum
public enum CountEventType {

    COUNT_EVENT_ALWAYS,
    COUNT_EVENT_DELTA_IN,
    COUNT_EVENT_DELTA_OUT,
    COUNT_EVENT_DELTA_SUM_IN_OUT,
    COUNT_EVENT_DELTA_MAX_IN_OUT;

    public String value() {
        return name();
    }

    public static CountEventType fromValue(String v) {
        return valueOf(v);
    }

}
