//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DigitalInputEventType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="DigitalInputEventType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="DIGITAL_INPUT_EVENT_INACTIVE"/>
 *     &lt;enumeration value="DIGITAL_INPUT_EVENT_ACTIVE"/>
 *     &lt;enumeration value="DIGITAL_INPUT_EVENT_ANY"/>
 *     &lt;enumeration value="DIGITAL_INPUT_EVENT_IGNORE"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "DigitalInputEventType")
@XmlEnum
public enum DigitalInputEventType {

    DIGITAL_INPUT_EVENT_INACTIVE,
    DIGITAL_INPUT_EVENT_ACTIVE,
    DIGITAL_INPUT_EVENT_ANY,
    DIGITAL_INPUT_EVENT_IGNORE;

    public String value() {
        return name();
    }

    public static DigitalInputEventType fromValue(String v) {
        return valueOf(v);
    }

}
