//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for EventTrigger complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="EventTrigger">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="count_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}CountEvent"/>
 *         &lt;element name="fill_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}FillEvent"/>
 *         &lt;element name="digital_input_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}DigitalInputEvent"/>
 *         &lt;element name="one_time_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}OneTimeEvent"/>
 *         &lt;element name="osd_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}OSD_Event"/>
 *         &lt;element name="current_object_list_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}CurrentObjectListEvent"/>
 *         &lt;element name="clear_zone_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ClearZoneEvent"/>
 *         &lt;element name="count_channels_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}CountChannelsEvent"/>
 *         &lt;element name="zone_channels_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ZoneChannelsEvent"/>
 *         &lt;element name="feature_changed_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}FeatureChangedEvent"/>
 *         &lt;element name="wireless_tracking_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}WirelessTrackingEvent"/>
 *         &lt;element name="zone_statistics_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ZoneStatisticsEvent"/>
 *         &lt;element name="zone_object_list_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ZoneObjectListEvent"/>
 *         &lt;element name="alert_event" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}AlertEvent"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "EventTrigger", propOrder = {
    "countEvent",
    "fillEvent",
    "digitalInputEvent",
    "oneTimeEvent",
    "osdEvent",
    "currentObjectListEvent",
    "clearZoneEvent",
    "countChannelsEvent",
    "zoneChannelsEvent",
    "featureChangedEvent",
    "wirelessTrackingEvent",
    "zoneStatisticsEvent",
    "zoneObjectListEvent",
    "alertEvent"
})
public class EventTrigger {

    @XmlElement(name = "count_event")
    protected CountEvent countEvent;
    @XmlElement(name = "fill_event")
    protected FillEvent fillEvent;
    @XmlElement(name = "digital_input_event")
    protected DigitalInputEvent digitalInputEvent;
    @XmlElement(name = "one_time_event")
    protected OneTimeEvent oneTimeEvent;
    @XmlElement(name = "osd_event")
    protected OSDEvent osdEvent;
    @XmlElement(name = "current_object_list_event")
    protected CurrentObjectListEvent currentObjectListEvent;
    @XmlElement(name = "clear_zone_event")
    protected ClearZoneEvent clearZoneEvent;
    @XmlElement(name = "count_channels_event")
    protected CountChannelsEvent countChannelsEvent;
    @XmlElement(name = "zone_channels_event")
    protected ZoneChannelsEvent zoneChannelsEvent;
    @XmlElement(name = "feature_changed_event")
    protected FeatureChangedEvent featureChangedEvent;
    @XmlElement(name = "wireless_tracking_event")
    protected WirelessTrackingEvent wirelessTrackingEvent;
    @XmlElement(name = "zone_statistics_event")
    protected ZoneStatisticsEvent zoneStatisticsEvent;
    @XmlElement(name = "zone_object_list_event")
    protected ZoneObjectListEvent zoneObjectListEvent;
    @XmlElement(name = "alert_event")
    protected AlertEvent alertEvent;

    /**
     * Gets the value of the countEvent property.
     * 
     * @return
     *     possible object is
     *     {@link CountEvent }
     *     
     */
    public CountEvent getCountEvent() {
        return countEvent;
    }

    /**
     * Sets the value of the countEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountEvent }
     *     
     */
    public void setCountEvent(CountEvent value) {
        this.countEvent = value;
    }

    /**
     * Gets the value of the fillEvent property.
     * 
     * @return
     *     possible object is
     *     {@link FillEvent }
     *     
     */
    public FillEvent getFillEvent() {
        return fillEvent;
    }

    /**
     * Sets the value of the fillEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillEvent }
     *     
     */
    public void setFillEvent(FillEvent value) {
        this.fillEvent = value;
    }

    /**
     * Gets the value of the digitalInputEvent property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalInputEvent }
     *     
     */
    public DigitalInputEvent getDigitalInputEvent() {
        return digitalInputEvent;
    }

    /**
     * Sets the value of the digitalInputEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalInputEvent }
     *     
     */
    public void setDigitalInputEvent(DigitalInputEvent value) {
        this.digitalInputEvent = value;
    }

    /**
     * Gets the value of the oneTimeEvent property.
     * 
     * @return
     *     possible object is
     *     {@link OneTimeEvent }
     *     
     */
    public OneTimeEvent getOneTimeEvent() {
        return oneTimeEvent;
    }

    /**
     * Sets the value of the oneTimeEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link OneTimeEvent }
     *     
     */
    public void setOneTimeEvent(OneTimeEvent value) {
        this.oneTimeEvent = value;
    }

    /**
     * Gets the value of the osdEvent property.
     * 
     * @return
     *     possible object is
     *     {@link OSDEvent }
     *     
     */
    public OSDEvent getOsdEvent() {
        return osdEvent;
    }

    /**
     * Sets the value of the osdEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link OSDEvent }
     *     
     */
    public void setOsdEvent(OSDEvent value) {
        this.osdEvent = value;
    }

    /**
     * Gets the value of the currentObjectListEvent property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentObjectListEvent }
     *     
     */
    public CurrentObjectListEvent getCurrentObjectListEvent() {
        return currentObjectListEvent;
    }

    /**
     * Sets the value of the currentObjectListEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentObjectListEvent }
     *     
     */
    public void setCurrentObjectListEvent(CurrentObjectListEvent value) {
        this.currentObjectListEvent = value;
    }

    /**
     * Gets the value of the clearZoneEvent property.
     * 
     * @return
     *     possible object is
     *     {@link ClearZoneEvent }
     *     
     */
    public ClearZoneEvent getClearZoneEvent() {
        return clearZoneEvent;
    }

    /**
     * Sets the value of the clearZoneEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearZoneEvent }
     *     
     */
    public void setClearZoneEvent(ClearZoneEvent value) {
        this.clearZoneEvent = value;
    }

    /**
     * Gets the value of the countChannelsEvent property.
     * 
     * @return
     *     possible object is
     *     {@link CountChannelsEvent }
     *     
     */
    public CountChannelsEvent getCountChannelsEvent() {
        return countChannelsEvent;
    }

    /**
     * Sets the value of the countChannelsEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountChannelsEvent }
     *     
     */
    public void setCountChannelsEvent(CountChannelsEvent value) {
        this.countChannelsEvent = value;
    }

    /**
     * Gets the value of the zoneChannelsEvent property.
     * 
     * @return
     *     possible object is
     *     {@link ZoneChannelsEvent }
     *     
     */
    public ZoneChannelsEvent getZoneChannelsEvent() {
        return zoneChannelsEvent;
    }

    /**
     * Sets the value of the zoneChannelsEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZoneChannelsEvent }
     *     
     */
    public void setZoneChannelsEvent(ZoneChannelsEvent value) {
        this.zoneChannelsEvent = value;
    }

    /**
     * Gets the value of the featureChangedEvent property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureChangedEvent }
     *     
     */
    public FeatureChangedEvent getFeatureChangedEvent() {
        return featureChangedEvent;
    }

    /**
     * Sets the value of the featureChangedEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureChangedEvent }
     *     
     */
    public void setFeatureChangedEvent(FeatureChangedEvent value) {
        this.featureChangedEvent = value;
    }

    /**
     * Gets the value of the wirelessTrackingEvent property.
     * 
     * @return
     *     possible object is
     *     {@link WirelessTrackingEvent }
     *     
     */
    public WirelessTrackingEvent getWirelessTrackingEvent() {
        return wirelessTrackingEvent;
    }

    /**
     * Sets the value of the wirelessTrackingEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link WirelessTrackingEvent }
     *     
     */
    public void setWirelessTrackingEvent(WirelessTrackingEvent value) {
        this.wirelessTrackingEvent = value;
    }

    /**
     * Gets the value of the zoneStatisticsEvent property.
     * 
     * @return
     *     possible object is
     *     {@link ZoneStatisticsEvent }
     *     
     */
    public ZoneStatisticsEvent getZoneStatisticsEvent() {
        return zoneStatisticsEvent;
    }

    /**
     * Sets the value of the zoneStatisticsEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZoneStatisticsEvent }
     *     
     */
    public void setZoneStatisticsEvent(ZoneStatisticsEvent value) {
        this.zoneStatisticsEvent = value;
    }

    /**
     * Gets the value of the zoneObjectListEvent property.
     * 
     * @return
     *     possible object is
     *     {@link ZoneObjectListEvent }
     *     
     */
    public ZoneObjectListEvent getZoneObjectListEvent() {
        return zoneObjectListEvent;
    }

    /**
     * Sets the value of the zoneObjectListEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZoneObjectListEvent }
     *     
     */
    public void setZoneObjectListEvent(ZoneObjectListEvent value) {
        this.zoneObjectListEvent = value;
    }

    /**
     * Gets the value of the alertEvent property.
     * 
     * @return
     *     possible object is
     *     {@link AlertEvent }
     *     
     */
    public AlertEvent getAlertEvent() {
        return alertEvent;
    }

    /**
     * Sets the value of the alertEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertEvent }
     *     
     */
    public void setAlertEvent(AlertEvent value) {
        this.alertEvent = value;
    }

}
