//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotificationContainer complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotificationContainer">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="count_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}CountNotification"/>
 *         &lt;element name="fill_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}FillNotification"/>
 *         &lt;element name="digital_input_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}DigitalInputNotification"/>
 *         &lt;element name="alive_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}AliveNotification"/>
 *         &lt;element name="curr_objlist_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}CurrentObjectListNotification"/>
 *         &lt;element name="hist_objlist_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}HistoricObjectListNotification"/>
 *         &lt;element name="startup_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}StartupNotification"/>
 *         &lt;element name="clear_zone_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ClearZoneNotification"/>
 *         &lt;element name="count_channels_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}CountChannelsNotification"/>
 *         &lt;element name="zone_channels_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ZoneChannelsNotification"/>
 *         &lt;element name="features_info_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}FeatureInfoNotification"/>
 *         &lt;element name="wireless_tracking_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}WirelessTrackingNotification"/>
 *         &lt;element name="image_snapshots_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ImageSnapshotsNotification"/>
 *         &lt;element name="zone_statistics_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ZoneStatisticsNotification"/>
 *         &lt;element name="zone_object_list_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ZoneObjectListNotification"/>
 *         &lt;element name="alert_info_notification" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}AlertInfoNotification"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationContainer", propOrder = {
    "countNotification",
    "fillNotification",
    "digitalInputNotification",
    "aliveNotification",
    "currObjlistNotification",
    "histObjlistNotification",
    "startupNotification",
    "clearZoneNotification",
    "countChannelsNotification",
    "zoneChannelsNotification",
    "featuresInfoNotification",
    "wirelessTrackingNotification",
    "imageSnapshotsNotification",
    "zoneStatisticsNotification",
    "zoneObjectListNotification",
    "alertInfoNotification"
})
public class NotificationContainer {

    @XmlElement(name = "count_notification")
    protected CountNotification countNotification;
    @XmlElement(name = "fill_notification")
    protected FillNotification fillNotification;
    @XmlElement(name = "digital_input_notification")
    protected DigitalInputNotification digitalInputNotification;
    @XmlElement(name = "alive_notification")
    protected AliveNotification aliveNotification;
    @XmlElement(name = "curr_objlist_notification")
    protected CurrentObjectListNotification currObjlistNotification;
    @XmlElement(name = "hist_objlist_notification")
    protected HistoricObjectListNotification histObjlistNotification;
    @XmlElement(name = "startup_notification")
    protected StartupNotification startupNotification;
    @XmlElement(name = "clear_zone_notification")
    protected ClearZoneNotification clearZoneNotification;
    @XmlElement(name = "count_channels_notification")
    protected CountChannelsNotification countChannelsNotification;
    @XmlElement(name = "zone_channels_notification")
    protected ZoneChannelsNotification zoneChannelsNotification;
    @XmlElement(name = "features_info_notification")
    protected FeatureInfoNotification featuresInfoNotification;
    @XmlElement(name = "wireless_tracking_notification")
    protected WirelessTrackingNotification wirelessTrackingNotification;
    @XmlElement(name = "image_snapshots_notification")
    protected ImageSnapshotsNotification imageSnapshotsNotification;
    @XmlElement(name = "zone_statistics_notification")
    protected ZoneStatisticsNotification zoneStatisticsNotification;
    @XmlElement(name = "zone_object_list_notification")
    protected ZoneObjectListNotification zoneObjectListNotification;
    @XmlElement(name = "alert_info_notification")
    protected AlertInfoNotification alertInfoNotification;

    /**
     * Gets the value of the countNotification property.
     * 
     * @return
     *     possible object is
     *     {@link CountNotification }
     *     
     */
    public CountNotification getCountNotification() {
        return countNotification;
    }

    /**
     * Sets the value of the countNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountNotification }
     *     
     */
    public void setCountNotification(CountNotification value) {
        this.countNotification = value;
    }

    /**
     * Gets the value of the fillNotification property.
     * 
     * @return
     *     possible object is
     *     {@link FillNotification }
     *     
     */
    public FillNotification getFillNotification() {
        return fillNotification;
    }

    /**
     * Sets the value of the fillNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillNotification }
     *     
     */
    public void setFillNotification(FillNotification value) {
        this.fillNotification = value;
    }

    /**
     * Gets the value of the digitalInputNotification property.
     * 
     * @return
     *     possible object is
     *     {@link DigitalInputNotification }
     *     
     */
    public DigitalInputNotification getDigitalInputNotification() {
        return digitalInputNotification;
    }

    /**
     * Sets the value of the digitalInputNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link DigitalInputNotification }
     *     
     */
    public void setDigitalInputNotification(DigitalInputNotification value) {
        this.digitalInputNotification = value;
    }

    /**
     * Gets the value of the aliveNotification property.
     * 
     * @return
     *     possible object is
     *     {@link AliveNotification }
     *     
     */
    public AliveNotification getAliveNotification() {
        return aliveNotification;
    }

    /**
     * Sets the value of the aliveNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AliveNotification }
     *     
     */
    public void setAliveNotification(AliveNotification value) {
        this.aliveNotification = value;
    }

    /**
     * Gets the value of the currObjlistNotification property.
     * 
     * @return
     *     possible object is
     *     {@link CurrentObjectListNotification }
     *     
     */
    public CurrentObjectListNotification getCurrObjlistNotification() {
        return currObjlistNotification;
    }

    /**
     * Sets the value of the currObjlistNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CurrentObjectListNotification }
     *     
     */
    public void setCurrObjlistNotification(CurrentObjectListNotification value) {
        this.currObjlistNotification = value;
    }

    /**
     * Gets the value of the histObjlistNotification property.
     * 
     * @return
     *     possible object is
     *     {@link HistoricObjectListNotification }
     *     
     */
    public HistoricObjectListNotification getHistObjlistNotification() {
        return histObjlistNotification;
    }

    /**
     * Sets the value of the histObjlistNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link HistoricObjectListNotification }
     *     
     */
    public void setHistObjlistNotification(HistoricObjectListNotification value) {
        this.histObjlistNotification = value;
    }

    /**
     * Gets the value of the startupNotification property.
     * 
     * @return
     *     possible object is
     *     {@link StartupNotification }
     *     
     */
    public StartupNotification getStartupNotification() {
        return startupNotification;
    }

    /**
     * Sets the value of the startupNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link StartupNotification }
     *     
     */
    public void setStartupNotification(StartupNotification value) {
        this.startupNotification = value;
    }

    /**
     * Gets the value of the clearZoneNotification property.
     * 
     * @return
     *     possible object is
     *     {@link ClearZoneNotification }
     *     
     */
    public ClearZoneNotification getClearZoneNotification() {
        return clearZoneNotification;
    }

    /**
     * Sets the value of the clearZoneNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClearZoneNotification }
     *     
     */
    public void setClearZoneNotification(ClearZoneNotification value) {
        this.clearZoneNotification = value;
    }

    /**
     * Gets the value of the countChannelsNotification property.
     * 
     * @return
     *     possible object is
     *     {@link CountChannelsNotification }
     *     
     */
    public CountChannelsNotification getCountChannelsNotification() {
        return countChannelsNotification;
    }

    /**
     * Sets the value of the countChannelsNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link CountChannelsNotification }
     *     
     */
    public void setCountChannelsNotification(CountChannelsNotification value) {
        this.countChannelsNotification = value;
    }

    /**
     * Gets the value of the zoneChannelsNotification property.
     * 
     * @return
     *     possible object is
     *     {@link ZoneChannelsNotification }
     *     
     */
    public ZoneChannelsNotification getZoneChannelsNotification() {
        return zoneChannelsNotification;
    }

    /**
     * Sets the value of the zoneChannelsNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZoneChannelsNotification }
     *     
     */
    public void setZoneChannelsNotification(ZoneChannelsNotification value) {
        this.zoneChannelsNotification = value;
    }

    /**
     * Gets the value of the featuresInfoNotification property.
     * 
     * @return
     *     possible object is
     *     {@link FeatureInfoNotification }
     *     
     */
    public FeatureInfoNotification getFeaturesInfoNotification() {
        return featuresInfoNotification;
    }

    /**
     * Sets the value of the featuresInfoNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link FeatureInfoNotification }
     *     
     */
    public void setFeaturesInfoNotification(FeatureInfoNotification value) {
        this.featuresInfoNotification = value;
    }

    /**
     * Gets the value of the wirelessTrackingNotification property.
     * 
     * @return
     *     possible object is
     *     {@link WirelessTrackingNotification }
     *     
     */
    public WirelessTrackingNotification getWirelessTrackingNotification() {
        return wirelessTrackingNotification;
    }

    /**
     * Sets the value of the wirelessTrackingNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link WirelessTrackingNotification }
     *     
     */
    public void setWirelessTrackingNotification(WirelessTrackingNotification value) {
        this.wirelessTrackingNotification = value;
    }

    /**
     * Gets the value of the imageSnapshotsNotification property.
     * 
     * @return
     *     possible object is
     *     {@link ImageSnapshotsNotification }
     *     
     */
    public ImageSnapshotsNotification getImageSnapshotsNotification() {
        return imageSnapshotsNotification;
    }

    /**
     * Sets the value of the imageSnapshotsNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImageSnapshotsNotification }
     *     
     */
    public void setImageSnapshotsNotification(ImageSnapshotsNotification value) {
        this.imageSnapshotsNotification = value;
    }

    /**
     * Gets the value of the zoneStatisticsNotification property.
     * 
     * @return
     *     possible object is
     *     {@link ZoneStatisticsNotification }
     *     
     */
    public ZoneStatisticsNotification getZoneStatisticsNotification() {
        return zoneStatisticsNotification;
    }

    /**
     * Sets the value of the zoneStatisticsNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZoneStatisticsNotification }
     *     
     */
    public void setZoneStatisticsNotification(ZoneStatisticsNotification value) {
        this.zoneStatisticsNotification = value;
    }

    /**
     * Gets the value of the zoneObjectListNotification property.
     * 
     * @return
     *     possible object is
     *     {@link ZoneObjectListNotification }
     *     
     */
    public ZoneObjectListNotification getZoneObjectListNotification() {
        return zoneObjectListNotification;
    }

    /**
     * Sets the value of the zoneObjectListNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZoneObjectListNotification }
     *     
     */
    public void setZoneObjectListNotification(ZoneObjectListNotification value) {
        this.zoneObjectListNotification = value;
    }

    /**
     * Gets the value of the alertInfoNotification property.
     * 
     * @return
     *     possible object is
     *     {@link AlertInfoNotification }
     *     
     */
    public AlertInfoNotification getAlertInfoNotification() {
        return alertInfoNotification;
    }

    /**
     * Sets the value of the alertInfoNotification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AlertInfoNotification }
     *     
     */
    public void setAlertInfoNotification(AlertInfoNotification value) {
        this.alertInfoNotification = value;
    }

}
