//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for NotificationWithOSDState complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="NotificationWithOSDState">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}NotificationBase">
 *       &lt;attribute name="osd_state" use="required" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}OSD_State" />
 *       &lt;attribute name="osd_error_detail" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NotificationWithOSDState")
@XmlSeeAlso({
    ClearZoneNotification.class,
    CurrentObjectListNotification.class,
    ZoneChannelsNotification.class,
    WirelessTrackingNotification.class,
    CountNotification.class,
    FillNotification.class,
    CountChannelsNotification.class,
    ExtendedNotificationBase.class
})
public abstract class NotificationWithOSDState
    extends NotificationBase
{

    @XmlAttribute(name = "osd_state", required = true)
    protected OSDState osdState;
    @XmlAttribute(name = "osd_error_detail")
    protected String osdErrorDetail;

    /**
     * Gets the value of the osdState property.
     * 
     * @return
     *     possible object is
     *     {@link OSDState }
     *     
     */
    public OSDState getOsdState() {
        return osdState;
    }

    /**
     * Sets the value of the osdState property.
     * 
     * @param value
     *     allowed object is
     *     {@link OSDState }
     *     
     */
    public void setOsdState(OSDState value) {
        this.osdState = value;
    }

    /**
     * Gets the value of the osdErrorDetail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOsdErrorDetail() {
        return osdErrorDetail;
    }

    /**
     * Sets the value of the osdErrorDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOsdErrorDetail(String value) {
        this.osdErrorDetail = value;
    }

}
