//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OSD_State.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="OSD_State">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="OSD_STATE_OK"/>
 *     &lt;enumeration value="OSD_STATE_ERROR_SENSOR_FAIL"/>
 *     &lt;enumeration value="OSD_STATE_WARNING_DARK"/>
 *     &lt;enumeration value="OSD_STATE_ERROR_DARK"/>
 *     &lt;enumeration value="OSD_STATE_WARNING_BRIGHT"/>
 *     &lt;enumeration value="OSD_STATE_ERROR_BRIGHT"/>
 *     &lt;enumeration value="OSD_STATE_NOT_AVAIL"/>
 *     &lt;enumeration value="OSD_STATE_INVALID"/>
 *     &lt;enumeration value="OSD_ERROR_COVERED"/>
 *     &lt;enumeration value="OSD_ERROR_TOO_DARK"/>
 *     &lt;enumeration value="OSD_ERROR_TOO_BRIGHT"/>
 *     &lt;enumeration value="OSD_ERROR"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "OSD_State")
@XmlEnum
public enum OSDState {

    OSD_STATE_OK,
    OSD_STATE_ERROR_SENSOR_FAIL,
    OSD_STATE_WARNING_DARK,
    OSD_STATE_ERROR_DARK,
    OSD_STATE_WARNING_BRIGHT,
    OSD_STATE_ERROR_BRIGHT,
    OSD_STATE_NOT_AVAIL,
    OSD_STATE_INVALID,
    OSD_ERROR_COVERED,
    OSD_ERROR_TOO_DARK,
    OSD_ERROR_TOO_BRIGHT,
    OSD_ERROR;

    public String value() {
        return name();
    }

    public static OSDState fromValue(String v) {
        return valueOf(v);
    }

}
