//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SOAP_DeviceError.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="SOAP_DeviceError">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="SOAP_DEVICE_OK"/>
 *     &lt;enumeration value="SOAP_ERROR_UNKNOWN_TASK"/>
 *     &lt;enumeration value="SOAP_ERROR_UNKNOWN_PARAM"/>
 *     &lt;enumeration value="SOAP_ERROR_OUT_OF_RESSOURCES"/>
 *     &lt;enumeration value="SOAP_ERROR_NO_LICENSE"/>
 *     &lt;enumeration value="SOAP_ERROR_TASK_EXECUTION"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "SOAP_DeviceError")
@XmlEnum
public enum SOAPDeviceError {

    SOAP_DEVICE_OK,
    SOAP_ERROR_UNKNOWN_TASK,
    SOAP_ERROR_UNKNOWN_PARAM,
    SOAP_ERROR_OUT_OF_RESSOURCES,
    SOAP_ERROR_NO_LICENSE,
    SOAP_ERROR_TASK_EXECUTION;

    public String value() {
        return name();
    }

    public static SOAPDeviceError fromValue(String v) {
        return valueOf(v);
    }

}
