//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for StartupNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="StartupNotification">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}ExtendedNotificationBase">
 *       &lt;attribute name="reboot_type" use="required" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}RebootType" />
 *       &lt;attribute name="xml_version" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "StartupNotification")
public class StartupNotification
    extends ExtendedNotificationBase
{

    @XmlAttribute(name = "reboot_type", required = true)
    protected RebootType rebootType;
    @XmlAttribute(name = "xml_version", required = true)
    protected String xmlVersion;

    /**
     * Gets the value of the rebootType property.
     * 
     * @return
     *     possible object is
     *     {@link RebootType }
     *     
     */
    public RebootType getRebootType() {
        return rebootType;
    }

    /**
     * Sets the value of the rebootType property.
     * 
     * @param value
     *     allowed object is
     *     {@link RebootType }
     *     
     */
    public void setRebootType(RebootType value) {
        this.rebootType = value;
    }

    /**
     * Gets the value of the xmlVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlVersion() {
        return xmlVersion;
    }

    /**
     * Sets the value of the xmlVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlVersion(String value) {
        this.xmlVersion = value;
    }

}
