//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaskSubscribeFill complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskSubscribeFill">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}TaskSubscribeTriggeredSafe">
 *       &lt;sequence>
 *         &lt;element name="fill_region_id" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}FillRegionID"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskSubscribeFill", propOrder = {
    "fillRegionId"
})
public class TaskSubscribeFill
    extends TaskSubscribeTriggeredSafe
{

    @XmlElement(name = "fill_region_id", required = true)
    protected FillRegionID fillRegionId;

    /**
     * Gets the value of the fillRegionId property.
     * 
     * @return
     *     possible object is
     *     {@link FillRegionID }
     *     
     */
    public FillRegionID getFillRegionId() {
        return fillRegionId;
    }

    /**
     * Sets the value of the fillRegionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link FillRegionID }
     *     
     */
    public void setFillRegionId(FillRegionID value) {
        this.fillRegionId = value;
    }

}
