//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Task complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Task">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="task_type" use="required" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}TaskType" />
 *       &lt;attribute name="serverTask_ID" use="required" type="{http://www.w3.org/2001/XMLSchema}unsignedInt" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Task")
@XmlSeeAlso({
    TaskRequestUpdate.class,
    TaskDeleteAllNotifications.class,
    TaskSetDateTime.class,
    TaskDeleteAllTasks.class,
    TaskSetVideoRecording.class,
    TaskWithActivity.class,
    TaskSetDigitalOutput.class
})
public abstract class Task {

    @XmlAttribute(name = "task_type", required = true)
    protected TaskType taskType;
    @XmlAttribute(name = "serverTask_ID", required = true)
    @XmlSchemaType(name = "unsignedInt")
    protected long serverTaskID;

    /**
     * Gets the value of the taskType property.
     * 
     * @return
     *     possible object is
     *     {@link TaskType }
     *     
     */
    public TaskType getTaskType() {
        return taskType;
    }

    /**
     * Sets the value of the taskType property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskType }
     *     
     */
    public void setTaskType(TaskType value) {
        this.taskType = value;
    }

    /**
     * Gets the value of the serverTaskID property.
     * 
     */
    public long getServerTaskID() {
        return serverTaskID;
    }

    /**
     * Sets the value of the serverTaskID property.
     * 
     */
    public void setServerTaskID(long value) {
        this.serverTaskID = value;
    }

}
