//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TaskType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TaskType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TASK_STARTUP"/>
 *     &lt;enumeration value="TASK_UPDATE"/>
 *     &lt;enumeration value="TASK_COUNT"/>
 *     &lt;enumeration value="TASK_FILL_LEVEL"/>
 *     &lt;enumeration value="TASK_DIGIT_INPUT"/>
 *     &lt;enumeration value="TASK_DIGIT_OUTPUT"/>
 *     &lt;enumeration value="TASK_SET_DATE_TIME"/>
 *     &lt;enumeration value="TASK_CURRENT_OBJECT_LIST"/>
 *     &lt;enumeration value="TASK_HISTORIC_OBJECT_LIST"/>
 *     &lt;enumeration value="TASK_ALIVE"/>
 *     &lt;enumeration value="TASK_CLEAR_ZONE"/>
 *     &lt;enumeration value="TASK_COUNT_CHANNELS"/>
 *     &lt;enumeration value="TASK_ZONE_CHANNELS"/>
 *     &lt;enumeration value="TASK_FEATURES_INFO"/>
 *     &lt;enumeration value="TASK_DELETE_ALL_TASKS"/>
 *     &lt;enumeration value="TASK_DELETE_ALL_NOTIFICATIONS"/>
 *     &lt;enumeration value="TASK_WIRELESS_TRACKING"/>
 *     &lt;enumeration value="TASK_IMAGE_SNAPSHOTS"/>
 *     &lt;enumeration value="TASK_ZONE_STATISTICS"/>
 *     &lt;enumeration value="TASK_ZONE_OBJECT_LIST"/>
 *     &lt;enumeration value="TASK_ALERT_INFO"/>
 *     &lt;enumeration value="TASK_SET_VIDEO_RECORDING"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TaskType")
@XmlEnum
public enum TaskType {

    TASK_STARTUP,
    TASK_UPDATE,
    TASK_COUNT,
    TASK_FILL_LEVEL,
    TASK_DIGIT_INPUT,
    TASK_DIGIT_OUTPUT,
    TASK_SET_DATE_TIME,
    TASK_CURRENT_OBJECT_LIST,
    TASK_HISTORIC_OBJECT_LIST,
    TASK_ALIVE,
    TASK_CLEAR_ZONE,
    TASK_COUNT_CHANNELS,
    TASK_ZONE_CHANNELS,
    TASK_FEATURES_INFO,
    TASK_DELETE_ALL_TASKS,
    TASK_DELETE_ALL_NOTIFICATIONS,
    TASK_WIRELESS_TRACKING,
    TASK_IMAGE_SNAPSHOTS,
    TASK_ZONE_STATISTICS,
    TASK_ZONE_OBJECT_LIST,
    TASK_ALERT_INFO,
    TASK_SET_VIDEO_RECORDING;

    public String value() {
        return name();
    }

    public static TaskType fromValue(String v) {
        return valueOf(v);
    }

}
