//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.19 at 10:08:23 PM BST 
//


package teste;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WirelessTrackingNotification complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WirelessTrackingNotification">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}NotificationWithOSDState">
 *       &lt;sequence>
 *         &lt;element name="wireless_tracking_results" type="{http://www.aglaia-gmbh.de/xml/2013/05/17/BaSS_SOAPd.xsd}WirelessTrackingResults"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "WirelessTrackingNotification", propOrder = {
    "wirelessTrackingResults"
})
public class WirelessTrackingNotification
    extends NotificationWithOSDState
{

    @XmlElement(name = "wireless_tracking_results", required = true)
    protected WirelessTrackingResults wirelessTrackingResults;

    /**
     * Gets the value of the wirelessTrackingResults property.
     * 
     * @return
     *     possible object is
     *     {@link WirelessTrackingResults }
     *     
     */
    public WirelessTrackingResults getWirelessTrackingResults() {
        return wirelessTrackingResults;
    }

    /**
     * Sets the value of the wirelessTrackingResults property.
     * 
     * @param value
     *     allowed object is
     *     {@link WirelessTrackingResults }
     *     
     */
    public void setWirelessTrackingResults(WirelessTrackingResults value) {
        this.wirelessTrackingResults = value;
    }

}
